--CREATE DATABASE futbol; la he creado con el comando que utilizamos en la practica de futbol

COMMIT;
BEGIN;

CREATE TABLE IF NOT EXISTS Ligas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    numeroEquipos INT NOT NULL,
    pais VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS Equipos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    estadio VARCHAR(100),
    entrenador VARCHAR(100),
    ciudad VARCHAR(100),
    fundacion SMALLINT,
    idLiga BIGINT NOT NULL,
    FOREIGN KEY (idLiga) REFERENCES Ligas(id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS Jugadores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    dorsal INT NOT NULL,
    posicion VARCHAR(20) NOT NULL,
    nacionalidad VARCHAR(100),
    fechaNacimiento VARCHAR(100),
    idEquipo BIGINT NOT NULL,
    FOREIGN KEY (idEquipo) REFERENCES Equipos(id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

COMMIT;
BEGIN;

-- 1. INSERTAR LAS 5 GRANDES LIGAS
INSERT INTO Ligas (nombre, numeroEquipos, pais) VALUES 
('LaLiga EA Sports', 20, 'España'),
('Premier League', 20, 'Inglaterra'),
('Serie A', 20, 'Italia'),
('Bundesliga', 18, 'Alemania'),
('Ligue 1', 18, 'Francia');

-- 2. INSERTAR TODOS LOS EQUIPOS (Temporada 2025/2026)

-- ESPAÑA (idLiga: 1)
INSERT INTO Equipos (nombre, estadio, entrenador, ciudad, fundacion, idLiga) VALUES 
('Real Madrid', 'Santiago Bernabéu', 'Álvaro Arbeloa', 'Madrid', 1902, 1),
('FC Barcelona', 'Spotify Camp Nou', 'Hansi Flick', 'Barcelona', 1899, 1),
('Atlético de Madrid', 'Riyadh Air Metropolitano', 'Diego Simeone', 'Madrid', 1903, 1),
('Real Sociedad', 'Reale Arena', 'Imanol Alguacil', 'San Sebastián', 1909, 1),
('Athletic Club', 'San Mamés', 'Ernesto Valverde', 'Bilbao', 1898, 1),
('Girona FC', 'Montilivi', 'Míchel', 'Girona', 1930, 1),
('Real Betis', 'Benito Villamarín', 'Manuel Pellegrini', 'Sevilla', 1907, 1),
('Villarreal CF', 'Estadio de la Cerámica', 'Marcelino García Toral', 'Villarreal', 1923, 1),
('Valencia CF', 'Mestalla', 'Rubén Baraja', 'Valencia', 1919, 1),
('Sevilla FC', 'Ramón Sánchez-Pizjuán', 'Xavi García Pimienta', 'Sevilla', 1890, 1),
('CA Osasuna', 'El Sadar', 'Vicente Moreno', 'Pamplona', 1920, 1),
('Getafe CF', 'Coliseum', 'José Bordalás', 'Getafe', 1983, 1),
('RC Celta', 'Abanca-Balaídos', 'Claudio Giráldez', 'Vigo', 1923, 1),
('RCD Mallorca', 'Son Moix', 'Jagoba Arrasate', 'Palma', 1916, 1),
('Rayo Vallecano', 'Vallecas', 'Iñigo Pérez', 'Madrid', 1924, 1),
('UD Las Palmas', 'Estadio de Gran Canaria', 'Diego Martínez', 'Las Palmas', 1949, 1),
('Deportivo Alavés', 'Mendizorroza', 'Luis García Plaza', 'Vitoria', 1921, 1),
('CD Leganés', 'Butarque', 'Borja Jiménez', 'Leganés', 1928, 1),
('Real Valladolid', 'José Zorrilla', 'Paulo Pezzolano', 'Valladolid', 1928, 1),
('RCD Espanyol', 'Stage Front Stadium', 'Manolo González', 'Cornellà', 1900, 1);

-- INGLATERRA (idLiga: 2)
INSERT INTO Equipos (nombre, estadio, entrenador, ciudad, fundacion, idLiga) VALUES 
('Manchester City', 'Etihad Stadium', 'Pep Guardiola', 'Manchester', 1880, 2),
('Arsenal FC', 'Emirates Stadium', 'Mikel Arteta', 'Londres', 1886, 2),
('Liverpool FC', 'Anfield', 'Arne Slot', 'Liverpool', 1892, 2),
('Aston Villa', 'Villa Park', 'Unai Emery', 'Birmingham', 1874, 2),
('Tottenham Hotspur', 'Tottenham Stadium', 'Ange Postecoglou', 'Londres', 1882, 2),
('Chelsea FC', 'Stamford Bridge', 'Enzo Maresca', 'Londres', 1905, 2),
('Newcastle United', 'St James Park', 'Eddie Howe', 'Newcastle', 1892, 2),
('Manchester United', 'Old Trafford', 'Ruben Amorim', 'Manchester', 1878, 2),
('West Ham United', 'London Stadium', 'Julen Lopetegui', 'Londres', 1895, 2),
('Brighton & Hove Albion', 'Amex Stadium', 'Fabian Hürzeler', 'Brighton', 1901, 2),
('Fulham FC', 'Craven Cottage', 'Marco Silva', 'Londres', 1879, 2),
('Crystal Palace', 'Selhurst Park', 'Oliver Glasner', 'Londres', 1905, 2),
('Wolverhampton', 'Molineux Stadium', 'Gary ONeil', 'Wolverhampton', 1877, 2),
('AFC Bournemouth', 'Vitality Stadium', 'Andoni Iraola', 'Bournemouth', 1899, 2),
('Everton FC', 'Everton Stadium', 'Sean Dyche', 'Liverpool', 1878, 2),
('Brentford FC', 'Gtech Community', 'Thomas Frank', 'Londres', 1889, 2),
('Nottingham Forest', 'City Ground', 'Nuno Espírito Santo', 'Nottingham', 1865, 2),
('Leicester City', 'King Power Stadium', 'Steve Cooper', 'Leicester', 1884, 2),
('Ipswich Town', 'Portman Road', 'Kieran McKenna', 'Ipswich', 1878, 2),
('Southampton FC', 'St Marys Stadium', 'Russell Martin', 'Southampton', 1885, 2);

-- ITALIA (idLiga: 3)
INSERT INTO Equipos (nombre, estadio, entrenador, ciudad, fundacion, idLiga) VALUES 
('Inter de Milán', 'San Siro', 'Simone Inzaghi', 'Milán', 1908, 3),
('Juventus FC', 'Allianz Stadium', 'Thiago Motta', 'Turín', 1897, 3),
('AC Milan', 'San Siro', 'Paulo Fonseca', 'Milán', 1899, 3),
('Atalanta BC', 'Gewiss Stadium', 'Gian Piero Gasperini', 'Bérgamo', 1907, 3),
('SSC Napoli', 'Diego Maradona', 'Antonio Conte', 'Nápoles', 1926, 3),
('AS Roma', 'Stadio Olimpico', 'Claudio Ranieri', 'Roma', 1927, 3),
('SS Lazio', 'Stadio Olimpico', 'Marco Baroni', 'Roma', 1900, 3),
('Bologna FC', 'Renato DallAra', 'Vincenzo Italiano', 'Bolonia', 1909, 3),
('ACF Fiorentina', 'Artemio Franchi', 'Raffaele Palladino', 'Florencia', 1926, 3),
('Torino FC', 'Olimpico di Torino', 'Paolo Vanoli', 'Turín', 1906, 3),
('Monza', 'U-Power Stadium', 'Alessandro Nesta', 'Monza', 1912, 3),
('Genoa CFC', 'Luigi Ferraris', 'Alberto Gilardino', 'Génova', 1893, 3),
('Lecce', 'Via del Mare', 'Luca Gotti', 'Lecce', 1908, 3),
('Udinese Calcio', 'Bluenergy Stadium', 'Kosta Runjaić', 'Udine', 1896, 3),
('Cagliari Calcio', 'Unipol Domus', 'Davide Nicola', 'Cagliari', 1920, 3),
('Empoli FC', 'Carlo Castellani', 'Roberto D Aversa', 'Empoli', 1920, 3),
('Hellas Verona', 'Marcantonio Bentegodi', 'Paolo Zanetti', 'Verona', 1903, 3),
('Parma Calcio', 'Ennio Tardini', 'Fabio Pecchia', 'Parma', 1913, 3),
('Como 1907', 'Stadio Giuseppe Sinigaglia', 'Cesc Fàbregas', 'Como', 1907, 3),
('Venezia FC', 'Pier Luigi Penzo', 'Eusebio Di Francesco', 'Venecia', 1907, 3);

-- ALEMANIA (idLiga: 4)
INSERT INTO Equipos (nombre, estadio, entrenador, ciudad, fundacion, idLiga) VALUES 
('Bayer Leverkusen', 'BayArena', 'Xabi Alonso', 'Leverkusen', 1904, 4),
('Bayern Múnich', 'Allianz Arena', 'Vincent Kompany', 'Múnich', 1900, 4),
('Borussia Dortmund', 'Signal Iduna Park', 'Nuri Şahin', 'Dortmund', 1909, 4),
('RB Leipzig', 'Red Bull Arena', 'Marco Rose', 'Leipzig', 2009, 4),
('VfB Stuttgart', 'MHPArena', 'Sebastian Hoeneß', 'Stuttgart', 1893, 4),
('Eintracht Frankfurt', 'Deutsche Bank Park', 'Dino Toppmöller', 'Fráncfort', 1899, 4),
('TSG Hoffenheim', 'PreZero Arena', 'Christian Ilzer', 'Sinsheim', 1899, 4),
('SC Freiburg', 'Europa-Park Stadion', 'Julian Schuster', 'Friburgo', 1904, 4),
('Werder Bremen', 'Weserstadion', 'Ole Werner', 'Bremen', 1899, 4),
('FC Augsburg', 'WWK Arena', 'Jess Thorup', 'Augsburgo', 1907, 4),
('VfL Wolfsburg', 'Volkswagen Arena', 'Ralph Hasenhüttl', 'Wolfsburgo', 1945, 4),
('Mainz 05', 'Mewa Arena', 'Bo Henriksen', 'Maguncia', 1905, 4),
('Borussia M’gladbach', 'Borussia-Park', 'Gerardo Seoane', 'Mönchengladbach', 1900, 4),
('Union Berlin', 'An der Alten Försterei', 'Bo Svensson', 'Berlín', 1966, 4),
('Heidenheim', 'Voith-Arena', 'Frank Schmidt', 'Heidenheim', 1846, 4),
('FC St. Pauli', 'Millerntor-Stadion', 'Alexander Blessin', 'Hamburgo', 1910, 4),
('Holstein Kiel', 'Holstein-Stadion', 'Marcel Rapp', 'Kiel', 1900, 4),
('VfL Bochum', 'Vonovia Ruhrstadion', 'Dieter Hecking', 'Bochum', 1848, 4);

-- FRANCIA (idLiga: 5)
INSERT INTO Equipos (nombre, estadio, entrenador, ciudad, fundacion, idLiga) VALUES 
('Paris Saint-Germain', 'Parc des Princes', 'Luis Enrique', 'París', 1970, 5),
('AS Mónaco', 'Stade Louis II', 'Adi Hütter', 'Mónaco', 1924, 5),
('Olympique de Marsella', 'Vélodrome', 'Roberto De Zerbi', 'Marsella', 1899, 5),
('Lille OSC', 'Decathlon Arena', 'Bruno Génésio', 'Lille', 1944, 5),
('OGC Niza', 'Allianz Riviera', 'Franck Haise', 'Niza', 1904, 5),
('Olympique de Lyon', 'Groupama Stadium', 'Pierre Sage', 'Lyon', 1950, 5),
('RC Lens', 'Stade Bollaert-Delelis', 'Will Still', 'Lens', 1906, 5),
('Stade de Reims', 'Stade Auguste-Delaune', 'Luka Elsner', 'Reims', 1931, 5),
('Stade Rennais', 'Roazhon Park', 'Jorge Sampaoli', 'Rennes', 1901, 5),
('Toulouse FC', 'Stadium de Toulouse', 'Carles Martínez', 'Toulouse', 1937, 5),
('Montpellier HSC', 'Stade de la Mosson', 'Jean-Louis Gasset', 'Montpellier', 1919, 5),
('RC Strasbourg', 'Stade de la Meinau', 'Liam Rosenior', 'Estrasburgo', 1906, 5),
('FC Nantes', 'Stade de la Beaujoire', 'Antoine Kombouaré', 'Nantes', 1943, 5),
('Le Havre AC', 'Stade Océane', 'Didier Digard', 'Le Havre', 1872, 5),
('AJ Auxerre', 'Stade de l Abbé-Deschamps', 'Christophe Pélissier', 'Auxerre', 1905, 5),
('Angers SCO', 'Stade Raymond Kopa', 'Alexandre Dujeux', 'Angers', 1919, 5),
('AS Saint-Étienne', 'Stade Geoffroy-Guichard', 'Olivier Dall Oglio', 'Saint-Étienne', 1933, 5),
('Stade Brestois', 'Stade Francis-Le Blé', 'Eric Roy', 'Brest', 1950, 5);

-- LALIGA EA SPORTS (IDs 1-20)
INSERT INTO Jugadores (nombre, dorsal, posicion, nacionalidad, fechaNacimiento, idEquipo) VALUES 
( 'T. Courtois', 1, 'Portero', 'Belga', '1992-05-11', 1), ('J. Bellingham', 5, 'Centrocampista', 'Inglesa', '2003-06-29', 1), ('K. Mbappé', 9, 'Delantero', 'Francesa', '1998-12-20', 1),
( 'Ter Stegen', 1, 'Portero', 'Alemana', '1992-04-30', 2), ('Gavi', 6, 'Centrocampista', 'Española', '2004-08-05', 2), ('Lamine Yamal', 19, 'Delantero', 'Española', '2007-07-13', 2),
( 'J. Oblak', 13, 'Portero', 'Eslovena', '1993-01-07', 3), ('Koke', 6, 'Centrocampista', 'Española', '1992-01-08', 3), ('Julián Álvarez', 19, 'Delantero', 'Argentina', '2000-01-31', 3),
( 'A. Remiro', 1, 'Portero', 'Española', '1995-03-24', 4), ('M. Zubimendi', 4, 'Centrocampista', 'Española', '1999-02-02', 4), ('M. Oyarzabal', 10, 'Delantero', 'Española', '1997-04-21', 4),
( 'Unai Simón', 1, 'Portero', 'Española', '1997-06-11', 5), ('I. Williams', 9, 'Delantero', 'Ghanesa', '1994-06-15', 5), ('Nico Williams', 11, 'Delantero', 'Española', '2002-07-12', 5),
( 'P. Gazzaniga', 13, 'Portero', 'Argentina', '1992-01-02', 6), ('Yangel Herrera', 21, 'Centrocampista', 'Venezolana', '1998-01-07', 6), ('Bryan Gil', 20, 'Delantero', 'Española', '2001-02-11', 6),
( 'Rui Silva', 1, 'Portero', 'Portuguesa', '1994-02-07', 7), ('Isco Alarcón', 22, 'Centrocampista', 'Española', '1992-04-21', 7), ('Cedric Bakambu', 11, 'Delantero', 'Congoleña', '1991-04-11', 7),
( 'Diego Conde', 1, 'Portero', 'Española', '1998-10-28', 8), ('Dani Parejo', 10, 'Centrocampista', 'Española', '1989-04-16', 8), ('Gerard Moreno', 7, 'Delantero', 'Española', '1992-04-07', 8),
( 'Mamardashvili', 25, 'Portero', 'Georgiana', '2000-09-29', 9), ('Javi Guerra', 8, 'Centrocampista', 'Española', '2003-05-13', 9), ('Hugo Duro', 9, 'Delantero', 'Española', '1999-11-10', 9),
( 'Nyland', 13, 'Portero', 'Noruega', '1990-09-10', 10), ('Saúl Ñíguez', 17, 'Centrocampista', 'Española', '1994-11-21', 10), ('Dodi Lukebakio', 11, 'Delantero', 'Belga', '1997-09-24', 10),
( 'S. Herrera', 1, 'Portero', 'Española', '1993-06-05', 11), ('Lucas Torró', 6, 'Centrocampista', 'Española', '1994-07-19', 11), ('Ante Budimir', 17, 'Delantero', 'Croata', '1991-07-22', 11),
( 'David Soria', 13, 'Portero', 'Española', '1993-04-04', 12), ('Mauro Arambarri', 8, 'Centrocampista', 'Uruguaya', '1995-09-30', 12), ('Borja Mayoral', 9, 'Delantero', 'Española', '1997-04-05', 12),
( 'Vicente Guaita', 13, 'Portero', 'Española', '1987-01-10', 13), ('Ilaix Moriba', 14, 'Centrocampista', 'Guineana', '2003-01-19', 13), ('Iago Aspas', 10, 'Delantero', 'Española', '1987-08-01', 13),
( 'Dominik Greif', 1, 'Portero', 'Eslovaca', '1997-04-06', 14), ('Sergi Darder', 10, 'Centrocampista', 'Española', '1993-12-22', 14), ('Vedat Muriqi', 7, 'Delantero', 'Kosovar', '1994-04-24', 14),
( 'Augusto Batalla', 13, 'Portero', 'Argentina', '1996-04-30', 15), ('James Rodríguez', 10, 'Centrocampista', 'Colombiana', '1991-07-12', 15), ('Isi Palazón', 7, 'Delantero', 'Española', '1994-12-27', 15),
( 'Jasper Cillessen', 1, 'Portero', 'Neerlandesa', '1989-04-22', 16), ('Kirian Rodríguez', 20, 'Centrocampista', 'Española', '1996-03-05', 16), ('Oli McBurnie', 9, 'Delantero', 'Escocesa', '1996-06-04', 16),
( 'Antonio Sivera', 1, 'Portero', 'Española', '1996-08-11', 17), ('Ander Guevara', 6, 'Centrocampista', 'Española', '1997-07-07', 17), ('Toni Martínez', 11, 'Delantero', 'Española', '1997-06-30', 17),
( 'Juan Soriano', 1, 'Portero', 'Española', '1997-08-23', 18), ('Seydouba Cissé', '18', 'Centrocampista', 'Guineana', '2001-02-10', 18), ('Sébastien Haller', '18', 'Delantero', 'Marfileña', '1994-06-22', 18),
( 'Karl Hein', 1, 'Portero', 'Estonia', '2002-04-13', 19), ('Kike Pérez', 4, 'Centrocampista', 'Española', '1997-02-10', 19), ('Raúl Moro', 11, 'Delantero', 'Española', '2002-12-05', 19),
( 'Joan García', 1, 'Portero', 'Española', '2001-05-04', 20), ('Alex Král', 20, 'Centrocampista', 'Checa', '1998-05-19', 20), ('Alejo Véliz', 9, 'Delantero', 'Argentina', '2003-09-19', 20);

-- PREMIER LEAGUE (IDs 21-40)
INSERT INTO Jugadores (nombre, dorsal, posicion, nacionalidad, fechaNacimiento, idEquipo) VALUES 
( 'Ederson', 31, 'Portero', 'Brasileña', '1993-08-17', 21), ('Rodri', 16, 'Centrocampista', 'Española', '1996-06-22', 21), ('E. Haaland', 9, 'Delantero', 'Noruega', '2000-07-21', 21),
( 'David Raya', 22, 'Portero', 'Española', '1995-09-15', 22), ('M. Ødegaard', 8, 'Centrocampista', 'Noruega', '1998-12-17', 22), ('B. Saka', 7, 'Delantero', 'Inglesa', '2001-09-05', 22),
( 'Alisson', 1, 'Portero', 'Brasileña', '1992-10-02', 23), ('A. Mac Allister', 10, 'Centrocampista', 'Argentina', '1998-12-24', 23), ('M. Salah', 11, 'Delantero', 'Egipcia', '1992-06-15', 23),
( 'E. Martínez', 23, 'Portero', 'Argentina', '1992-09-02', 24), ('Youri Tielemans', 8, 'Centrocampista', 'Belga', '1997-05-07', 24), ('Ollie Watkins', 11, 'Delantero', 'Inglesa', '1995-12-30', 24),
( 'G. Vicario', 1, 'Portero', 'Italiana', '1996-10-07', 25), ('James Maddison', 10, 'Centrocampista', 'Inglesa', '1996-11-23', 25), ('Son Heung-min', 7, 'Delantero', 'Coreana', '1992-07-08', 25),
( 'Robert Sánchez', 1, 'Portero', 'Española', '1997-11-18', 26), ('Cole Palmer', 20, 'Centrocampista', 'Inglesa', '2002-05-06', 26), ('Nicolas Jackson', 15, 'Delantero', 'Senegalesa', '2001-06-20', 26),
( 'Nick Pope', 22, 'Portero', 'Inglesa', '1992-04-19', 27), ('Bruno Guimarães', 39, 'Centrocampista', 'Brasileña', '1997-11-16', 27), ('Alexander Isak', 14, 'Delantero', 'Sueca', '1999-09-21', 27),
( 'André Onana', 24, 'Portero', 'Camerunesa', '1996-04-02', 28), ('Bruno Fernandes', 8, 'Centrocampista', 'Portuguesa', '1994-09-08', 28), ('Alejandro Garnacho', 17, 'Delantero', 'Argentina', '2004-07-01', 28),
( 'A. Areola', 23, 'Portero', 'Francesa', '1993-02-27', 29), ('Lucas Paquetá', 10, 'Centrocampista', 'Brasileña', '1997-08-27', 29), ('Jarrod Bowen', 20, 'Delantero', 'Inglesa', '1996-12-20', 29),
( 'Bart Verbruggen', 1, 'Portero', 'Neerlandesa', '2002-08-18', 30), ('Carlos Baleba', 20, 'Centrocampista', 'Camerunesa', '2004-01-03', 30), ('Joao Pedro', 9, 'Delantero', 'Brasileña', '2001-09-26', 30),
( 'Bernd Leno', 1, 'Portero', 'Alemana', '1992-03-04', 31), ('Andreas Pereira', 15, 'Centrocampista', 'Brasileña', '1996-01-01', 31), ('Raúl Jiménez', 7, 'Delantero', 'Mexicana', '1991-05-05', 31),
( 'Dean Henderson', 1, 'Portero', 'Inglesa', '1997-03-12', 32), ('Adam Wharton', 20, 'Centrocampista', 'Inglesa', '2004-02-06', 32), ('Jean-P. Mateta', 14, 'Delantero', 'Francesa', '1997-06-28', 32),
( 'José Sá', 1, 'Portero', 'Portuguesa', '1993-01-17', 33), ('Joao Gomes', 8, 'Centrocampista', 'Brasileña', '2001-02-12', 33), ('Matheus Cunha', 10, 'Delantero', 'Brasileña', '1999-05-27', 33),
( 'Kepa Arrizabalaga', 13, 'Portero', 'Española', '1994-10-03', 34), ('Justin Kluivert', 19, 'Centrocampista', 'Neerlandesa', '1999-05-05', 34), ('Evanilson', 9, 'Delantero', 'Brasileña', '1999-10-06', 34),
( 'Jordan Pickford', 1, 'Portero', 'Inglesa', '1994-03-07', 35), ('Iliman Ndiaye', 10, 'Centrocampista', 'Senegalesa', '2000-03-06', 35), ('Dominic Calvert-Lewin', 9, 'Delantero', 'Inglesa', '1997-03-16', 35),
( 'Mark Flekken', 1, 'Portero', 'Neerlandesa', '1993-06-13', 36), ('Mikkel Damsgaard', 24, 'Centrocampista', 'Danesa', '2000-07-03', 36), ('Bryan Mbeumo', 19, 'Delantero', 'Camerunesa', '1999-08-07', 36),
( 'Matz Sels', 26, 'Portero', 'Belga', '1992-02-26', 37), ('Morgan Gibbs-White', 10, 'Centrocampista', 'Inglesa', '2000-01-27', 37), ('Chris Wood', 11, 'Delantero', 'Neozelandesa', '1991-12-07', 37),
( 'Mads Hermansen', 30, 'Portero', 'Danesa', '2000-07-11', 38), ('Harry Winks', 8, 'Centrocampista', 'Inglesa', '1996-02-02', 38), ('Jamie Vardy', 9, 'Delantero', 'Inglesa', '1987-01-11', 38),
( 'Arijanet Muric', 1, 'Portero', 'Kosovar', '1998-11-07', 39), ('Kalvin Phillips', 8, 'Centrocampista', 'Inglesa', '1995-12-02', 39), ('Liam Delap', 19, 'Delantero', 'Inglesa', '2003-02-08', 39),
( 'Aaron Ramsdale', 30, 'Portero', 'Inglesa', '1998-05-14', 40), ('Adam Lallana', 10, 'Centrocampista', 'Inglesa', '1988-05-10', 40), ('Ben Brereton Díaz', 17, 'Delantero', 'Chilena', '1999-04-18', 40);

-- SERIE A (IDs 41-60)
INSERT INTO Jugadores (nombre, dorsal, posicion, nacionalidad, fechaNacimiento, idEquipo) VALUES 
( 'Yann Sommer', 1, 'Portero', 'Suiza', '1988-12-17', 41), ('Hakan Calhanoglu', 20, 'Centrocampista', 'Turca', '1994-02-08', 41), ('Lautaro Martínez', 10, 'Delantero', 'Argentina', '1997-08-22', 41),
( 'M. Di Gregorio', 29, 'Portero', 'Italiana', '1997-07-27', 42), ('Teun Koopmeiners', 8, 'Centrocampista', 'Neerlandesa', '1998-02-28', 42), ('Kenan Yildiz', 10, 'Delantero', 'Turca', '2005-05-04', 42),
( 'Mike Maignan', 16, 'Portero', 'Francesa', '1995-07-03', 43), ('Tijjani Reijnders', 14, 'Centrocampista', 'Neerlandesa', '1998-07-29', 43), ('Rafael Leao', 10, 'Delantero', 'Portuguesa', '1999-06-10', 43),
( 'Marco Carnesecchi', 29, 'Portero', 'Italiana', '2000-07-01', 44), ('Mario Pasalic', 8, 'Centrocampista', 'Croata', '1995-02-09', 44), ('Ademola Lookman', 11, 'Delantero', 'Nigeriana', '1997-10-20', 44),
( 'Alex Meret', 1, 'Portero', 'Italiana', '1997-03-22', 45), ('S. McTominay', 8, 'Centrocampista', 'Escocesa', '1996-12-08', 45), ('R. Lukaku', 11, 'Delantero', 'Belga', '1993-05-13', 45),
( 'Mile Svilar', 99, 'Portero', 'Serbiia', '1999-08-27', 46), ('Lorenzo Pellegrini', 7, 'Centrocampista', 'Italiana', '1996-06-19', 46), ('Paulo Dybala', 21, 'Delantero', 'Argentina', '1993-11-15', 46),
( 'Ivan Provedel', 94, 'Portero', 'Italiana', '1994-03-17', 47), ('Mattia Zaccagni', 10, 'Centrocampista', 'Italiana', '1995-06-16', 47), ('Taty Castellanos', 11, 'Delantero', 'Argentina', '1998-10-03', 47),
( 'Lukasz Skorupski', 1, 'Portero', 'Polaca', '1991-05-05', 48), ('Remo Freuler', 8, 'Centrocampista', 'Suiza', '1992-04-15', 48), ('Santiago Castro', 9, 'Delantero', 'Argentina', '2004-09-18', 48),
( 'David De Gea', 43, 'Portero', 'Española', '1990-11-07', 49), ('Yacine Adli', 29, 'Centrocampista', 'Francesa', '2000-07-29', 49), ('Moise Kean', 20, 'Delantero', 'Italiana', '2000-02-28', 49),
( 'Vanja Milinkovic-Savic', 32, 'Portero', 'Serbia', '1997-02-20', 50), ('Samuele Ricci', 28, 'Centrocampista', 'Italiana', '2001-08-21', 50), ('Duvan Zapata', 91, 'Delantero', 'Colombiana', '1991-04-01', 50),
( 'Stefano Turati', 30, 'Portero', 'Italiana', '2001-09-05', 51), ('Matteo Pessina', 32, 'Centrocampista', 'Italiana', '1997-04-21', 51), ('Dany Mota', 47, 'Delantero', 'Portuguesa', '1998-05-02', 51),
( 'Pierluigi Gollini', 95, 'Portero', 'Italiana', '1995-03-18', 52), ('Ruslan Malinovskyi', 17, 'Centrocampista', 'Ucraniana', '1993-05-04', 52), ('Andrea Pinamonti', 19, 'Delantero', 'Italiana', '1999-05-19', 52),
( 'Wladimiro Falcone', 30, 'Portero', 'Italiana', '1995-04-12', 53), ('Ylber Ramadani', 20, 'Centrocampista', 'Albanesa', '1996-04-12', 53), ('Nikola Krstovic', 9, 'Delantero', 'Montenegrina', '2000-04-05', 53),
( 'Maduka Okoye', 40, 'Portero', 'Nigeriana', '1999-08-28', 54), ('Sandi Lovric', 8, 'Centrocampista', 'Eslovena', '1998-03-28', 54), ('Lorenzo Lucca', 17, 'Delantero', 'Italiana', '2000-09-10', 54),
( 'Simone Scuffet', 22, 'Portero', 'Italiana', '1996-05-31', 55), ('Razvan Marin', 18, 'Centrocampista', 'Rumana', '1996-05-23', 55), ('Zito Luvumbo', 77, 'Delantero', 'Angoleña', '2002-03-09', 55),
( 'Vasquez', 23, 'Portero', 'Colombiana', '1998-03-01', 56), ('Liam Henderson', 8, 'Centrocampista', 'Escocesa', '1996-04-25', 56), ('Sebastiano Esposito', 9, 'Delantero', 'Italiana', '2002-07-02', 56),
( 'Lorenzo Montipò', 1, 'Portero', 'Italiana', '1996-02-20', 57), ('Ondrej Duda', 33, 'Centrocampista', 'Eslovaca', '1994-12-05', 57), ('Casper Tengstedt', 11, 'Delantero', 'Danesa', '2000-06-01', 57),
( 'Zion Suzuki', 1, 'Portero', 'Japonesa', '2002-08-21', 58), ('Hernani', 27, 'Centrocampista', 'Brasileña', '1994-03-27', 58), ('Dennis Man', 98, 'Delantero', 'Rumana', '1998-08-26', 58),
( 'Pepe Reina', 25, 'Portero', 'Española', '1982-08-31', 59), ('Nico Paz', 79, 'Centrocampista', 'Argentina', '2004-09-08', 59), ('Patrick Cutrone', 10, 'Delantero', 'Italiana', '1998-01-03', 59),
( 'Jesse Joronen', 1, 'Portero', 'Finlandesa', '1993-03-21', 60), ('Gianluca Busio', 6, 'Centrocampista', 'Estadounidense', '2002-05-28', 60), ('Joel Pohjanpalo', 20, 'Delantero', 'Finlandesa', '1994-09-13', 60);

-- BUNDESLIGA (IDs 61-78)
INSERT INTO Jugadores (nombre, dorsal, posicion, nacionalidad, fechaNacimiento, idEquipo) VALUES 
( 'Hradecky', 1, 'Portero', 'Finlandesa', '1989-11-24', 61), ('Xhaka', 34, 'Centrocampista', 'Suiza', '1992-09-27', 61), ('Florian Wirtz', 10, 'Centrocampista', 'Alemana', '2003-05-03', 61),
( 'Manuel Neuer', 1, 'Portero', 'Alemana', '1986-03-27', 62), ('Jamal Musiala', 42, 'Centrocampista', 'Alemana', '2003-02-26', 62), ('Harry Kane', 9, 'Delantero', 'Inglesa', '1993-07-28', 62),
( 'Gregor Kobel', 1, 'Portero', 'Suiza', '1997-12-06', 63), ('Julian Brandt', 10, 'Centrocampista', 'Alemana', '1996-05-02', 63), ('Serhou Guirassy', 9, 'Delantero', 'Guineana', '1996-03-12', 63),
( 'Péter Gulácsi', 1, 'Portero', 'Húngara', '1990-05-06', 64), ('Xavi Simons', 20, 'Centrocampista', 'Neerlandesa', '2003-04-21', 64), ('Loïs Openda', 11, 'Delantero', 'Belga', '2000-02-16', 64),
( 'A. Nübel', 33, 'Portero', 'Alemana', '1996-09-30', 65), ('Angelo Stiller', 6, 'Centrocampista', 'Alemana', '2001-04-04', 65), ('Deniz Undav', 26, 'Delantero', 'Alemana', '1996-07-19', 65),
( 'Kevin Trapp', 1, 'Portero', 'Alemana', '1990-07-08', 66), ('Mario Götze', 27, 'Centrocampista', 'Alemana', '1992-06-03', 66), ('Omar Marmoush', 7, 'Delantero', 'Egipcia', '1999-02-07', 66),
( 'Oliver Baumann', 1, 'Portero', 'Alemana', '1990-06-02', 67), ('Andrej Kramaric', 27, 'Delantero', 'Croata', '1991-06-19', 67), ('M. Berisha', 11, 'Delantero', 'Alemana', '1998-05-11', 67),
( 'Noah Atubolu', 1, 'Portero', 'Alemana', '2002-05-25', 68), ('Vincenzo Grifo', 32, 'Centrocampista', 'Italiana', '1993-04-07', 68), ('Michael Gregoritsch', 38, 'Delantero', 'Austríaca', '1994-04-18', 68),
( 'Michael Zetterer', 1, 'Portero', 'Alemana', '1995-07-12', 69), ('Jens Stage', 6, 'Centrocampista', 'Danesa', '1996-11-08', 69), ('Marvin Ducksch', 7, 'Delantero', 'Alemana', '1994-03-07', 69),
( 'Nediljko Labrovic', 1, 'Portero', 'Croata', '1999-10-10', 70), ('Frank Onyeka', 33, 'Centrocampista', 'Nigeriana', '1998-01-01', 70), ('Phillip Tietz', 9, 'Delantero', 'Alemana', '1997-07-09', 70),
( 'Kamil Grabara', 1, 'Portero', 'Polaca', '1999-01-08', 71), ('Maximilian Arnold', 27, 'Centrocampista', 'Alemana', '1994-05-27', 71), ('Mohamed Amoura', 17, 'Delantero', 'Argelina', '2000-05-09', 71),
( 'Robin Zentner', 27, 'Portero', 'Alemana', '1994-10-28', 72), ('Nadiem Amiri', 18, 'Centrocampista', 'Alemana', '1996-10-27', 72), ('Jonathan Burkardt', 29, 'Delantero', 'Alemana', '2000-07-11', 72),
( 'Moritz Nicolas', 33, 'Portero', 'Alemana', '1997-10-21', 73), ('Julian Weigl', 8, 'Centrocampista', 'Alemana', '1995-09-08', 73), ('Tim Kleindienst', 11, 'Delantero', 'Alemana', '1995-08-31', 73),
( 'Frederik Rönnow', 1, 'Portero', 'Danesa', '1992-08-04', 74), ('László Bénes', 19, 'Centrocampista', 'Eslovaca', '1997-09-09', 74), ('Yorbe Vertessen', 11, 'Delantero', 'Belga', '2001-01-08', 74),
( 'Kevin Müller', 1, 'Portero', 'Alemana', '1991-04-11', 75), ('Paul Wanner', 14, 'Centrocampista', 'Alemana', '2005-12-23', 75), ('Marvin Pieringer', 9, 'Delantero', 'Alemana', '1999-10-04', 75),
( 'Nikola Vasilj', 22, 'Portero', 'Bosnia', '1995-12-02', 76), ('Jackson Irvine', 7, 'Centrocampista', 'Australiana', '1993-03-07', 76), ('Johannes Eggestein', 11, 'Delantero', 'Alemana', '1998-05-08', 76),
( 'Timon Weiner', 1, 'Portero', 'Alemana', '1999-01-18', 77), ('Lewis Holtby', 10, 'Centrocampista', 'Alemana', '1990-09-18', 77), ('Fiete Arp', 7, 'Delantero', 'Alemana', '2000-01-06', 77),
( 'Patrick Drewes', 1, 'Portero', 'Alemana', '1993-02-04', 78), ('Anthony Losilla', 8, 'Centrocampista', 'Francesa', '1986-03-10', 78), ('Philipp Hofmann', 9, 'Delantero', 'Alemana', '1993-03-30', 78);

-- LIGUE 1 (IDs 79-96)
INSERT INTO Jugadores (nombre, dorsal, posicion, nacionalidad, fechaNacimiento, idEquipo) VALUES 
( 'Donnarumma', 1, 'Portero', 'Italiana', '1999-02-25', 79), ('Vitinha', 17, 'Centrocampista', 'Portuguesa', '2000-02-13', 79), ('B. Barcola', 29, 'Delantero', 'Francesa', '2002-09-02', 79),
( 'Radoslaw Majecki', 1, 'Portero', 'Polaca', '1999-11-16', 80), ('Denis Zakaria', 6, 'Centrocampista', 'Suiza', '1996-11-20', 80), ('Breel Embolo', 36, 'Delantero', 'Suiza', '1997-02-14', 80),
( 'Geronimo Rulli', 1, 'Portero', 'Argentina', '1992-05-20', 81), ('Adrien Rabiot', 25, 'Centrocampista', 'Francesa', '1995-04-03', 81), ('Mason Greenwood', 10, 'Delantero', 'Inglesa', '2001-10-01', 81),
( 'Lucas Chevalier', 30, 'Portero', 'Francesa', '2001-11-06', 82), ('Angel Gomes', 10, 'Centrocampista', 'Inglesa', '2000-08-31', 82), ('Jonathan David', 9, 'Delantero', 'Canadiense', '2000-01-14', 82),
( 'Marcin Bulka', 1, 'Portero', 'Polaca', '1999-10-04', 83), ('Tanguy Ndombélé', 22, 'Centrocampista', 'Francesa', '1996-12-28', 83), ('Youssoufa Moukoko', 15, 'Delantero', 'Alemana', '2004-11-20', 83),
( 'Lucas Perri', 1, 'Portero', 'Brasileña', '1997-12-10', 84), ('Maxence Caqueret', 6, 'Centrocampista', 'Francesa', '2000-02-15', 84), ('A. Lacazette', 10, 'Delantero', 'Francesa', '1991-05-28', 84),
( 'Brice Samba', 30, 'Portero', 'Francesa', '1994-04-25', 85), ('Andy Diouf', 18, 'Centrocampista', 'Francesa', '2003-05-17', 85), ('Mbala Nzola', 8, 'Delantero', 'Angoleña', '1996-09-15', 85),
( 'Yehvann Diouf', 94, 'Portero', 'Francesa', '1999-11-16', 86), ('Teddy Teuma', 10, 'Centrocampista', 'Maltesa', '1993-09-30', 86), ('Junya Ito', 7, 'Delantero', 'Japonesa', '1993-03-09', 86),
( 'Steve Mandanda', 30, 'Portero', 'Francesa', '1985-03-28', 87), ('Ludovic Blas', 11, 'Centrocampista', 'Francesa', '1997-12-31', 87), ('Amine Gouiri', 10, 'Delantero', 'Argelina', '2000-02-16', 87),
( 'Guillaume Restes', 50, 'Portero', 'Francesa', '2005-03-11', 88), ('Cristian Cásseres', 15, 'Centrocampista', 'Venezolana', '2000-01-20', 88), ('Zakaria Aboukhlal', 7, 'Delantero', 'Marroquí', '2000-02-18', 88),
( 'Benjamin Lecomte', 40, 'Portero', 'Francesa', '1991-04-26', 89), ('Téji Savanier', 11, 'Centrocampista', 'Francesa', '1991-12-22', 89), ('Akor Adams', 8, 'Delantero', 'Nigeriana', '2000-01-29', 89),
( 'Djordje Petrovic', 1, 'Portero', 'Serbia', '1999-10-08', 90), ('Andrey Santos', 8, 'Centrocampista', 'Brasileña', '2004-05-03', 90), ('Sebastian Nanasi', 15, 'Delantero', 'Sueca', '2002-05-16', 90),
( 'Alban Lafont', 1, 'Portero', 'Francesa', '1999-01-23', 91), ('Pedro Chirivella', 5, 'Centrocampista', 'Española', '1997-05-23', 91), ('Mostafa Mohamed', 31, 'Delantero', 'Egipcia', '1997-11-28', 91),
( 'Arthur Desmas', 1, 'Portero', 'Francesa', '1994-04-07', 92), ('Abdoulaye Touré', 22, 'Centrocampista', 'Guineana', '1994-03-03', 92), ('André Ayew', 28, 'Delantero', 'Ghanesa', '1989-12-17', 92),
( 'Donovan Léon', 16, 'Portero', 'Guayanesa', '1992-11-03', 93), ('Elisha Owusu', 42, 'Centrocampista', 'Ghanesa', '1997-11-07', 93), ('Gaëtan Perrin', 10, 'Delantero', 'Francesa', '1996-07-13', 93),
( 'Yahia Fofana', 30, 'Portero', 'Marfileña', '2000-08-21', 94), ('Himad Abdelli', 10, 'Centrocampista', 'Argelina', '1999-10-22', 94), ('Bamba Dieng', 9, 'Delantero', 'Senegalesa', '2000-03-23', 94),
( 'Gautier Larsonneur', 30, 'Portero', 'Francesa', '1997-02-23', 95), ('Benjamin Bouchouari', 6, 'Centrocampista', 'Marroquí', '2001-11-13', 95), ('Ibrahim Sissoko', 9, 'Delantero', 'Maliense', '1995-11-27', 95),
( 'Marco Bizot', 40, 'Portero', 'Neerlandesa', '1991-03-10', 96), ('Pierre Lees-Melou', 20, 'Centrocampista', 'Francesa', '1993-05-25', 96), ('Ludovic Ajorque', 19, 'Delantero', 'Francesa', '1994-02-25', 96);

COMMIT;